### ISSUE TITLE
Emulation slowdown

### ISSUE THREAD

**Issue by Kappa971** [nukeykt/Nuked-SC55#102]
Hi, with this midi track [D_NRFTL9.zip](https://github.com/user-attachments/files/17479532/D_NRFTL9.zip), taken from a midi pack for Doom No Rest for the Living, Nuked SC-55 (mk2) seems to play the track strangely, slows down and goes back to normal. Sound Canvas VA doesn't have this problem.
If I run two instances of Nuked SC-55 with Falcosoft MIDI Player, there is no slowdown.
Maybe this track is poorly composed? Polyphony? (I don't notice any cut notes) Or is it exposing an emulation issue? I don't know if this happens on real hardware. I also tried different buffer sizes ​​but the result doesn't change.

CPU R7 5700x, Windows 11.

I also attach the tracks recorded in ogg format with Nuked SC-55 and SCVA.
[D_NRFTL9_NukedSC.zip](https://github.com/user-attachments/files/17479563/D_NRFTL9_NukedSC.zip)
[D_NRFTL9_SCVA.zip](https://github.com/user-attachments/files/17479564/D_NRFTL9_SCVA.zip)

**Comment by mckuhei** [comment]
It seems that the MIDI transmission rate exceeds the limit. I also noticed this problem on *my* SC-88 Pro.

**Comment by Kappa971** [comment]
"MIDI is transmitted as asynchronous bytes at 31250 bits per second. One start bit, eight data bits, and one stop bit result in a maximum transmission rate of 3125 bytes per second." Where did you see that it is exceeding the transmission limit? Also Sound Canvas VA works well as well as the built-in Windows synthesizer. This is what LoopMIDI shows:
![image](https://github.com/user-attachments/assets/86520333-aa19-47f9-8a52-e4dbb076f96b)

It seems like the emulation is slowing down for some reason, but you say your SC-88 Pro has the same problem... Maybe it's another hardware limitation? On the other hand these midi were written in recent times without caring about the limitations of the old Roland modules...

**Comment by mckuhei** [comment]
If you have TMIDI Player, you can turn on "Adjust MIDI message transfer rate" so that you can see the "JAM" indicator flashing on the player. When the indicator is on, it means that the MIDI transmission rate exceeds the limit. At this time, TMIDI Player will reduce the MIDI transmission rate.
![image](https://github.com/user-attachments/assets/53526c5f-16a9-4500-9053-31a66462752b)
![image](https://github.com/user-attachments/assets/72b109d0-d8c4-4358-9dc8-72d6a10afa66)

**Comment by mckuhei** [comment]
Checkout this video:
https://github.com/user-attachments/assets/639fc2e6-d496-4735-90d7-c163d99c9852

**Comment by mckuhei** [comment]
By checking the MIDI file, I found two problems:
1. All channels are initialized in an instant and there are a lot of repeated events (MIDI files exported by FL Studio have this problem)
![image](https://github.com/user-attachments/assets/84560537-65d4-43a6-b364-2e453f8b3005)
2. Channel 3 is repeating a lot of Program Change events
![image](https://github.com/user-attachments/assets/7dc397df-8480-4462-8ff9-d4c9cf902160)

**Comment by Kappa971** [comment]
Ok so it's a badly programmed midi file, maybe I should report it on doomworld.com: https://www.doomworld.com/forum/topic/119301-no-rest-for-the-living-community-midi-pack-released/

**Comment by TorutheRedFox** [comment]
i have stutter problems playing passport.mid

i don't think this is necessarily a bad MIDI problem

**Comment by Kappa971** [comment]
As pointed out by @mckuhei, who is surely more expert than me (I'm not at all), that midi file has many uselessly repeated events that cause a slowdown of the emulator but also of the real hardware. The other tracks also have repeated events, in particular at the beginning (in fact Nuked SC-55 starts playing the midi track with a delay of some ms due to the initial "overcrowding"), so those midi are badly written but for some reason the other software synthesizers read them anyway without issues.
Nuked SC-55 emulates the hardware accurately and so the problems/errors of those tracks come out.

I played passport.mid with Nuked SC-55 in mk1 mode (mk2 doesn't assign some instruments, it doesn't support CTF and this track was probably not written for/with SC-55), I don't notice any problems.
I attach the .mid and pre-recorded .ogg file: [passport.zip](https://github.com/user-attachments/files/17498582/passport.zip)

**Comment by TorutheRedFox** [comment]
> As pointed out by @mckuhei, who is surely more expert than me (I'm not at all), that midi file has many uselessly repeated events that cause a slowdown of the emulator but also of the real hardware. The other tracks also have repeated events, in particular at the beginning (in fact Nuked SC-55 starts playing the midi track with a delay of some ms due to the initial "overcrowding"), so those midi are badly written but for some reason the other software synthesizers read them anyway without issues. Nuked SC-55 emulates the hardware accurately and so the problems/errors of those tracks come out.
> 
> I played passport.mid with Nuked SC-55 in mk1 mode (mk2 doesn't assign some instruments, it doesn't support CTF and this track was probably not written for/with SC-55), I don't notice any problems. I attach the .mid and pre-recorded .ogg file: [passport.zip](https://github.com/user-attachments/files/17498582/passport.zip)

sc-55mkii works fine with the midi shipped with windows ([passport.zip](https://github.com/user-attachments/files/17526719/passport.zip))

there's versions of the midi floating around that don't play nice with GS

some parts of the song are off-beat when played in the emulator, and I don't recall hearing such issues on actual hardware

**Comment by Kappa971** [comment]
> sc-55mkii works fine with the midi shipped with windows ([passport.zip](https://github.com/user-attachments/files/17526719/passport.zip))
> 
> there's versions of the midi floating around that don't play nice with GS
> 
> some parts of the song are off-beat when played in the emulator, and I don't recall hearing such issues on actual hardware

I took my passport.mid from a Windows 95 installation (if I remember correctly), in fact it is dated June 24, 1996. I found that on mk2 it doesn't work correctly because some instruments aren't recognized. With mk2 it works in GM mode.
Where did you get that file? On Windows 11 it is no longer there. Anyway I also recorded your .mid file to .ogg: [passport_NukedSC55mk2.zip](https://github.com/user-attachments/files/17527874/passport_NukedSC55mk2.zip). I may noticed a speed "variation" at 0:47 but I'm not sure. However it doesn't play as in your attached file. I'm on R7 5700x, if you're trying to use this emulator on an AMD Athlon 64, it's obviously going to be bad 😅

There's another emulator in development, `emusc`, that has the same goal as Munt: a "not accurate" but as close to the hardware sound as possible emulation that could be a good choice in the future (it's still incomplete), especially for resource usage or polyphony limits compared to Nuked SC-55.

**Comment by TorutheRedFox** [comment]
> > sc-55mkii works fine with the midi shipped with windows ([passport.zip](https://github.com/user-attachments/files/17526719/passport.zip))
> > there's versions of the midi floating around that don't play nice with GS
> > some parts of the song are off-beat when played in the emulator, and I don't recall hearing such issues on actual hardware
> 
> I took my passport.mid from a Windows 95 installation (if I remember correctly), in fact it is dated June 24, 1996. I found that on mk2 it doesn't work correctly because some instruments aren't recognized. With mk2 it works in GM mode. Where did you get that file? On Windows 11 it is no longer there. Anyway I also recorded your .mid file to .ogg: [passport_NukedSC55mk2.zip](https://github.com/user-attachments/files/17527874/passport_NukedSC55mk2.zip). I may noticed a speed "variation" at 0:47 but I'm not sure. However it doesn't play as in your attached file. I'm on R7 5700x, if you're trying to use this emulator on an AMD Athlon 64, it's obviously going to be bad 😅
> 
> There's another emulator in development, `emusc`, that has the same goal as Munt: a "not accurate" but as close to the hardware sound as possible emulation that could be a good choice in the future (it's still incomplete), especially for resource usage or polyphony limits compared to Nuked SC-55.

Windows NT 4.5, as for the CPU I'm running this on, it's a Core i5 (10300H)

**Comment by Kappa971** [comment]
> Windows NT 4.5, as for the CPU I'm running this on, it's a Core i5 (10300H)

That CPU seems to have slightly better performance than a 2013 Intel Core i7 4770k, maybe that's why you're having problems.
Try changing the buffer size with the `-ab:<page_size>` parameter. If I remember correctly the default is `512:32`, I keep it at `512:4` (so `-ab:512:4`) and it works fine for me. Try different values ​​and see if anything changes.
Also make sure there is no background process like Microsoft Defender hogging the CPU. Energy saving may also slow down performance.
