### ISSUE TITLE
Cannot build the binary without adding `/DWIN32_CONSOLE` flag

### ISSUE THREAD

**Issue by nvsofts** [nukeykt/Nuked-SC55#16]
If the flag is not added, this error occurred:
```
error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
```

**Comment by nukeykt** [comment]
@Wohlstand any idea?

**Comment by Wohlstand** [comment]
What the MSVC version? Actually need to supply `/DWIN32_WINDOWS` (`-mwindows` on MinGW-w64).

**Comment by Wohlstand** [comment]
Anyway... how do you even try to compile the thing?

**Comment by nvsofts** [comment]
I am using VS2022 and MSVC compiler 14.39.33519.
This problem was not resolved adding `/DWIN32_WINDOWS` to compiler flag.

**Comment by NicknineTheEagle** [comment]
On VS 2022, I have to go Properties -> Linker -> System and change SybSystem to Windows.

**Comment by nvsofts** [comment]
I used native CMake support on Visual Studio.

**Comment by 000MDK** [comment]
build on windows with [MSYS2](https://www.msys2.org/) works 
(use MINGW64 console)

prereqs:
```
update-core
pacman -Suy
pacman -S make gettext base-devel libtool pkg-config git mingw-w64-x86_64-cmake mingw-w64-x86_64-SDL2 mingw-w64-x86_64-toolchain
```


build with:
```
git clone https://github.com/nukeykt/Nuked-SC55.git
cd ./Nuked-SC55
cmake . -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
cmake --build .
```

**Comment by nvsofts** [comment]
Is using MSVC not intended?

**Comment by Wohlstand** [comment]
It should work with MSVC too, but it's not fully tested on my end (it's possible to try run the Visual Studio command prompt, and run CMake from it after changing directory into project's build directory). I need to boot my second machine to try verify this. Right now that table is busy by a chaos of things, so, I can't right now.

**Comment by 000MDK** [comment]
@Wohlstand I don't know yet if this is build-system related or to any of the latest code changes here:
any of my **builds are unusable as notes keep getting stuck - this does not happen with binary [release 0.1.1](https://github.com/nukeykt/Nuked-SC55/releases/tag/0.1.1)**
I'll look into it and report back

**Comment by 000MDK** [comment]
reporting back: built 0.1.1 nuked-sc55.exe is also 8484KB and has the same problem with stuck notes. FWIW building with UCRT works too and gives the same bad result.
I'm guessing something something about datatypes/a missing build flag from the top of my head - looking into that now.

**Comment by chunkyjackson** [comment]
> build on windows with [MSYS2](https://www.msys2.org/) succeeds (use MINGW64 console)
> 
> **_still, builds are practically unusable as notes keep getting stuck (tested with Raze and theForceEngine) though, this might just be a problem on my specific buildsystem - can someone confirm?_**
> 
> so some step still missing here
> 
> prereqs:
> 
> ```
> update-core
> pacman -Suy
> pacman -S make gettext base-devel libtool pkg-config git mingw-w64-x86_64-cmake mingw-w64-x86_64-SDL2 mingw-w64-x86_64-toolchain
> ```
> 
> build with:
> 
> ```
> git clone https://github.com/nukeykt/Nuked-SC55.git
> cd ./Nuked-SC55
> cmake . -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
> cmake --build .
> ```

You have a recursive repository in there so to pull the repository it should be the following...

git clone --recursive https://github.com/nukeykt/Nuked-SC55.git

I just built the current update and it does not have stuck note bug.

**Comment by Kappa971** [comment]
https://cplusplus.com/forum/windows/277119/
"you provided a WinMain() as if you were writing a GUI application."
Compilation seems to break at "utf8main_win32.cpp", Visual Studio can't find int main()

**Comment by NicknineTheEagle** [comment]
The code is set up to support both `main` and `WinMain`. The problem with is that it requires `WIN32_CONSOLE` preprocessor to enable `main` function which is not present by default despite CMake generating VS projects set to Console subsystem.

**Comment by Kappa971** [comment]
> The code is set up to support both `main` and `WinMain`. The problem with is that it requires `WIN32_CONSOLE` preprocessor to enable `main` function which is not present by default despite CMake generating VS projects set to Console subsystem.

How to enable `WIN32_CONSOLE` preprocessor?

**Comment by NicknineTheEagle** [comment]
> > The code is set up to support both `main` and `WinMain`. The problem with is that it requires `WIN32_CONSOLE` preprocessor to enable `main` function which is not present by default despite CMake generating VS projects set to Console subsystem.
> 
> How to enable `WIN32_CONSOLE` preprocessor?

I have to ask what you're doing in this thread if you don't even know what preprocessors are and how to enable them.
https://cplusplus.com/doc/tutorial/preprocessor/
https://stackoverflow.com/questions/51830325/how-to-add-preprocessor-definition-on-visual-studio-2017-c
https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html

**Comment by NicknineTheEagle** [comment]
> > I have to ask what you're doing in this thread if you don't even know what C++ preprocessors are and how to enable them. https://cplusplus.com/doc/tutorial/preprocessor/ https://stackoverflow.com/questions/51830325/how-to-add-preprocessor-definition-on-visual-studio-2017-c https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html
> 
> And I would like to ask you why you answer without giving a concrete answer or a solution...
> 
> Furthermore, I would recommend you to stay calm because I'm not your brother and I don't know you, and moreover I didn't insult you, you rude person. BYE BYE

I gave you several links that explain how to add preprocessors in Visual Studio, in GCC compiler (depends on what you're using to build) or directly in C++ code. If that's not concrete enough for you, I don't know what to tell you.
The broader point is, if you don't know the basics of C/C++ and aren't willing to learn then I don't understand why you're bothering trying to build this project from source code. There are pre-compiled builds at Releases page that anyone can use.

**Comment by Kappa971** [comment]
> I gave you several links that explain how to add preprocessors in Visual Studio, in GCC compiler (depends on what you're using to build) or directly in C++ code. If that's not concrete enough for you, I don't know what to tell you. The broader point is, if you don't know the basics of C/C++ and aren't willing to learn then I don't understand why you're bothering trying to build this project from source code. There are pre-compiled builds at Releases page that anyone can use.

I rewrote the answer more clearly, if you didn't understand before https://github.com/nukeykt/Nuked-SC55/issues/16#issuecomment-2073557778

I'm willing to learn but I can't stand people who respond in a pedantic and arrogant way to those who WANT to learn. 
Learn a little kindness if you don't want others to respond rudely to you like you did.

**Comment by NicknineTheEagle** [comment]
> > I gave you several links that explain how to add preprocessors in Visual Studio, in GCC compiler (depends on what you're using to build) or directly in C++ code. If that's not concrete enough for you, I don't know what to tell you. The broader point is, if you don't know the basics of C/C++ and aren't willing to learn then I don't understand why you're bothering trying to build this project from source code. There are pre-compiled builds at Releases page that anyone can use.
> 
> I rewrote the answer more clearly, if you didn't understand before [#16 (comment)](https://github.com/nukeykt/Nuked-SC55/issues/16#issuecomment-2073557778)
> 
> I'm willing to learn but I can't stand people who respond in a pedantic and arrogant way to those who WANT to learn. Learn a little kindness if you don't want others to respond rudely to you like you did.
> 
> The magic "command" is this and it goes in the file `CMakeLists.txt` `add_definitions(-DWIN32_CONSOLE)`

And I can't stand people who butt into subjects that go way over their heads and ask people around them to explain minute details to them when they got better things to do. Actual programmers knew what I was referring to in the original comment and don't need ABC explained to them. Again, this is a thread about building the project from source code which implies some level of baseline knowledge.

**Comment by Wohlstand** [comment]
> Compilation seems to break at "utf8main_win32.cpp", Visual Studio can't find `int main()`

Actually, the `utf8main.h` redefines the `main` by macro with a custom name to steal the "main" to self (the `utf8main_win32.cpp`). This is a module that forces command-line arguments to be in UTF-8 instead of ANSI charsets which is required to make the uniform behaviour on all supported platforms (everything but Windows uses UTF-8 charset for paths, and Windows is only "пуп земли" who uses ANSI for backward compatibility with legacy DOS and early Windows environments, and UTF-16 which is not widely used outside Windows: the UTF-32 or UTF-8 are used everywhere).

**Comment by Kappa971** [comment]
> And I can't stand people who butt into subjects that go way over their heads and ask people around them to explain minute details to them when they got better things to do. Actual programmers know what I was referring to in the original comment and don't need ABC explained to them. Again, this is a thread about building the project from source code which implies some level of baseline knowledge. If you're not a programmer, this thread doesn't concern you.

Don't be presumptuous, the solution was simple and even an inferior being like me found it. You have the solution, then do the PR instead of being arrogant with me.

You programmers are all the same... do they teach you at university to be like this?

**Comment by NicknineTheEagle** [comment]
> > And I can't stand people who butt into subjects that go way over their heads and ask people around them to explain minute details to them when they got better things to do. Actual programmers know what I was referring to in the original comment and don't need ABC explained to them. Again, this is a thread about building the project from source code which implies some level of baseline knowledge. If you're not a programmer, this thread doesn't concern you.
> 
> Don't be presumptuous, the solution was simple and even an inferior being like me found it.

This isn't the gotcha you think this is. If this topic was so simple why'd you feel the need to ask about it in the first place? Because you're not a programmer and butted into programming discussion asking for basics to be explained. Which is the point I was making in the first place.

> You have the solution, then do the PR instead of being arrogant with me.

We don't know the actual solution yet because we don't know why nukeykt has chosen to use WIN32_CONSOLE preprocessor and if it should actually be enabled by default. Adding it manually is just a workaround for the time being.

**Comment by Wohlstand** [comment]
> We don't know the actual solution yet because we don't know why nukeykt has chosen to use WIN32_CONSOLE preprocessor and if it should actually be enabled by default. Adding it manually is just a workaround for the time being.

During initial development he used the console dialogue to easily print any debug information directly. Do you really want to turn the application into GUI thing? Then I should provide the proper logger module that will output all debug stuff into the file then.

**Comment by NicknineTheEagle** [comment]
> > We don't know the actual solution yet because we don't know why nukeykt has chosen to use WIN32_CONSOLE preprocessor and if it should actually be enabled by default. Adding it manually is just a workaround for the time being.
> 
> During initial development he used the console dialogue to easily print any debug information directly. Do you really want to turn the application into GUI thing? Then I should provide the proper logger module that will output all debug stuff into the file then.

No, you misunderstood me, I don't mean why console app type is used. I mean WIN32_CONSOLE specifically, what's the deal with it? This doesn't seem to be a standard thing and it's not added by CMake scripts.

**Comment by NicknineTheEagle** [comment]
> > Compilation seems to break at "utf8main_win32.cpp", Visual Studio can't find `int main()`
> 
> Actually, the `utf8main.h` redefines the `main` by macro with a custom name to steal the "main" to self (the `utf8main_win32.cpp`). This is a module that forces command-line arguments to be in UTF-8 instead of ANSI charsets which is required to make the uniform behaviour on all supported platforms (everything but Windows uses UTF-8 charset for paths, and Windows is only "пуп земли" who uses ANSI for backward compatibility with legacy DOS and early Windows environments, and UTF-16 which is not widely used outside Windows: the UTF-32 or UTF-8 are used everywhere).

Right, but this hijack doesn't seem to work properly as it renders MSVC unable to find `main`. We're missing something.

**Comment by Wohlstand** [comment]
I do have some other applications that use the same utf8main, and they builds fine with MSVC, but mainly focused on the MinGW target because MSVC is a pain in templates functionality and some bugs.

**Comment by Wohlstand** [comment]
Anyway, I could try to debug the thing on Windows once I power on my testing machine (my main platform is Linux Mint, and I don't use Windows widely, but I have the second machine that I use to debug Windows cases including MSVC related stuff).

**Comment by NicknineTheEagle** [comment]
> I do have some other applications that use the same utf8main, and they builds fine with MSVC, but mainly focused on the MinGW target because MSVC is a pain in templates functionality and some bugs.

Mmm, I tried building with MSYS2 just now and it does seem to compile out of the box. Also, didn't notice that UTF8_Main is a thirdparty module at first. So this seems to be MSVC issue specifically? But official builds appear to be compiled with VS 2022 according to the header which makes it all the more confusing.

**Comment by Wohlstand** [comment]
The UTF8 Main is my addition that I added to force UTF8 encoding in command line arguments. Actually, I used MSVC not so often because I prefer MinGW/MinGW-w64 over MSVC, but all the cases where I used MSVC, do work just fine. Builds done by @nukeykt done by the separated build project that he did before I created the CMake build to maintain the cross-platform support.

**Comment by NicknineTheEagle** [comment]
Checking further, it looks like building under MSYS2 uses `WinMain` by default so the thing with WIN32_CONSOLE preprocessor doesn't become relevant.
On the flipside, generated VS project uses `main` by default (since they're set to Console subsystem which is fine) but `main` is not defined unless WIN32_CONSOLE is set so the build fails.

**Comment by Wohlstand** [comment]
On Linux/Mac is plain `main()` is used and it ALWAYS gives UTF-8 by default, so, nothing is needed.

**Comment by NicknineTheEagle** [comment]
> On Linux/Mac is plain `main()` is used and it ALWAYS gives UTF-8 by default, so, nothing is needed.

Yeah, that's what I said in edited post.

**Comment by Wohlstand** [comment]
> On the flip side, generated VS project uses `main` by default (since it's set to Console subsystem which is fine) but `main` is not defined unless WIN32_CONSOLE is set so the build fails.

Sounds like, on the CMake side is needed to explicitly tell that it's the `WIN32 console` thing, so, when generating MSVC project, it should take that thing already added.

**Comment by NicknineTheEagle** [comment]
> > On the flip side, generated VS project uses `main` by default (since it's set to Console subsystem which is fine) but `main` is not defined unless WIN32_CONSOLE is set so the build fails.
> 
> Sounds like, on the CMake side is needed to explicitly tell that it's the `WIN32 console` thing, so, when generating MSVC project, it should take that thing already added.

I think the proper solution would be to drop WIN32_CONSOLE if/else block and just define both `main` and `WinMain` and call the former from the latter.

**Comment by Wohlstand** [comment]
> I think the proper solution would be to drop WIN32_CONSOLE if/else block and just define both `main` and `WinMain` on Windows and call the former from the latter.

Or at utf8_main_win32.cpp, handle the `MSC_VER` macro, and if defined, use the `main()` as an entry point as it's no matter because arguments here gets being retrieved by the different way.

**Comment by NicknineTheEagle** [comment]
> > I think the proper solution would be to drop WIN32_CONSOLE if/else block and just define both `main` and `WinMain` on Windows and call the former from the latter.
> 
> Or at utf8_main_win32.cpp, handle the `MSC_VER` macro, and if defined, use the `main()` as an entry point as it's no matter because arguments here gets being retrieved by the different way.

You can't force a specific entry point type, MSVC uses either `WinMain` or `main` depending on what subsystem is selected in project's linker settings.
