### ISSUE TITLE
SC-88 compatibility in the future? 

### ISSUE THREAD

**Issue by MetalMaxMX** [nukeykt/Nuked-SC55#24]
Hello! 

I saw a commit that hinted a WIP of the CM-300 synthesizer. Then I was wondering if adding the Roland SC-88 in the future would also be a possibility/on the roadmap of this project? Or is it out of scope? Just wanting to know.

Cheers!
MetalMaxMX

**Comment by nukeykt** [comment]
SC-88 and newer use completely different chipset, so they are out of the scope
