### ISSUE TITLE
Hangs with a frozen window, doesn't respond to any signal other than SIGKILL

### ISSUE THREAD

**Issue by KynikossDragonn** [nukeykt/Nuked-SC55#25]
I'm on Void Linux, kernel 6.6.25_1 with GCC 13.2.0 and SDL2 2.30.1

I'm not sure what I'm doing wrong. It builds, I get lots of compiler warnings but no errors.

It also requests way too small a buffer causing PipeWire to use a excessive amount of CPU, I tried adjusting `audio_page_size` but the emulator just brings up a window with the "contents" of what was behind the screen when the window comes up and the emulator just uses a lot of CPU and seemingly does nothing.

All I get on the terminal is this:
```
$ ./nuked-sc55 
Base path is: ./nuked-sc55
Audio Requested: F=S16LSB, C=2, R=66207, B=1024
Audio Actual: F=S16LSB, C=2, R=66207, B=1024
Unknown write e400 4
Unknown write e403 1
Unknown write e406 0
Unknown write e407 0
Unknown write e406 40
Unknown write e403 1
Killed
```

Are these ROMs bad?
```
 32K Dec 24  1996 rom1.bin
512K Dec 24  1996 rom2.bin
4.0K Dec 24  1996 rom_sm.bin
2.0M Dec 24  1996 waverom1.bin
1.0M Dec 24  1996 waverom2.bin

8a1eb33c7599b746c0c50283e4349a1bb1773b5c0ec0e9661219bf6c067d2042  ./rom1.bin
a4c9fd821059054c7e7681d61f49ce6f42ed2fe407a7ec1ba0dfdc9722582ce0  ./rom2.bin
b0b5f865a403f7308b4be8d0ed3ba2ed1c22db881b8a8326769dea222f6431d8  ./rom_sm.bin
c6429e21b9b3a02fbd68ef0b2053668433bee0bccd537a71841bc70b8874243b  ./waverom1.bin
5b753f6cef4cfc7fcafe1430fecbb94a739b874e55356246a46abe24097ee491  ./waverom2.bin
```

**Comment by pachuco** [comment]
SHA-256? yes these are good ROMs.
The emulation is pretty CPU heavy, mind you.

**Comment by Karmeck** [comment]
The one thing I see missing in the terminal window, is what midi channel is being used.

**Comment by KynikossDragonn** [comment]
> The one thing I see missing in the terminal window, is what midi channel is being used.

I don't actually see any usable MIDI device show up in ALSA so I suppose it's locking up as it's trying to get the MIDI part setup but I don't know how to use gdb to breakpoint it to really see if that's the case.

**Comment by KynikossDragonn** [comment]
Okay, I was dumb and didn't notice this was building a additional file that needed to exist `back.data` and having that in the working directory makes this work, sorry for the confusion...

The instructions should probably point out "back.data" needs to exist in the working directory of the emulator; there's no error messages if that file is missing.
