### ISSUE TITLE
Program only accepts 1 command line argument

### ISSUE THREAD

**Issue by ColouMods** [nukeykt/Nuked-SC55#31]
Currently, it seems like only the first command line argument given the program is actually used, and any additional arguments are ignored. This makes it impossible to select both a MIDI input port and ROM set at the same time.

![Image demonstrating the issue.](https://github.com/nukeykt/Nuked-SC55/assets/32771001/14dd1df8-de50-43d4-aadc-3cfb86968ce9)

**Comment by nukeykt** [comment]
hmm, indeed
will release another hotfix asap
