### ISSUE TITLE
SC-55 MK1 error loop, emulation fails to start.

### ISSUE THREAD

**Issue by Karmeck** [nukeykt/Nuked-SC55#34]
![loop](https://github.com/nukeykt/Nuked-SC55/assets/33399802/96fa40cc-14fa-4604-80d1-720cdb852cbf)

with this file for rom1

Filesize 32.768 bytes
SHA1 bff554cd641360e359c13154bfa9d65fbf5f365dbff554cd641360e359c13154bfa9d65fbf5f365d

looking at the command window it just loops.

**Comment by Grieferus** [comment]
Are you sure you've got the exact control ROMs?

**Comment by ThatRetroGuy** [comment]
> Are you sure you've got the exact control ROMs?

where can i message you? these are from mame.

**Comment by nukeykt** [comment]
hmm, you use wrong rom files, should be
v1.2x SHA-1: DD01EC54027751C2F2F2E47BBB7A0BF3D1CA8AE2
v2.0 SHA-1: 76F646BC03F66DBEE7606F2181D4EA76F05ECE7D

**Comment by odiaboeeu** [comment]
> SHA-1: DD01EC54027751C2F2F2E47BBB7A0BF3D1CA8AE2

Could you put the CRC of the files?
