### ISSUE TITLE
How did you dump the internal rom off of the MCUs?

### ISSUE THREAD

**Issue by nikitalita** [nukeykt/Nuked-SC55#41]
I had tried to do this a while back by attempting to modify the control rom to dump the contents of the internal MCU ROM during a `DUMP ALL INSTRUMENTS` command through the MIDI out port, but I could never get it to work.

**Comment by Karmeck** [comment]
https://twitter.com/nukeykt/status/1752965047179981212?t=GLiMbIyF8ZYgI63yEdVqtQ&s=19

**Comment by nukeykt** [comment]
hitachi mcu was dumped by injecting dumper code to conrol ROM and read using logic analyzer. mitsubishi was dumped by injecting dumper to RAM and executing it using power glitching
