### ISSUE TITLE
Windows "default" Midi In port problem

### ISSUE THREAD

**Issue by Falcosoft** [nukeykt/Nuked-SC55#5]
Hi,
Actually on Windows there is no such thing as "default" Midi In port in the sense that you can select one in any way.
Contrary to Midi Out ports where originally there was a built-in Midi mapper until Win 8 (and Coolsoft Midi Mapper on Win8+) to select the default Midi Out port there is no way (and never was) to select default Midi In port. 
Currently Nuked-SC55 always opens port 0 that can be a hardware port if you have a soundcard with hardware Midi In capabilities.
It does not matter if you install LoopMidi or any other software loopback cables in such a system Midi In port 0 remains a hardware port.
In such systems this recommendation from the Readme does not work:
>  to use it with the other applications use external MIDI pipe software (e.g. loopMIDI).   

So it would be helpful if the Midi In port to be opened could be set some way (config file etc.) 

![image](https://github.com/nukeykt/Nuked-SC55/assets/40074203/135f3284-b8f6-4b65-8783-1073ba7beaa5)

**Comment by Falcosoft** [comment]
> Maybe it's not the same thing? I'm testing the emulator with Falcosoft MIDI Player.
Yep, it's not the same thing :)
Coolsoft Midi Mapper has noting to do with Midi In ports. It can only set the default Midi Out port.
You do not have a sound card that has a hardware Midi In port so your first (0) Midi In port is a LoopMidi port.

**Comment by Kappa971** [comment]
> 
> Coolsoft Midi Mapper has nothing to do with Midi In ports. It can only set the default Midi Out port. It seems your first (0) Midi In port is a LoopMidi port. Somehow your hardware Midi in port is not the 1st one. What does Falcosoft MIDI Player (x64) settings dialog show on the Midi In part? I mean this part:
> 
> ![image](https://private-user-images.githubusercontent.com/40074203/319246231-3c2b9170-db97-4ae5-963d-c29f9f334b3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTg3NTQsIm5iZiI6MTcxMjE1ODQ1NCwicGF0aCI6Ii80MDA3NDIwMy8zMTkyNDYyMzEtM2MyYjkxNzAtZGI5Ny00YWU1LTk2M2QtYzI5ZjlmMzM0YjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE1MzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMTU4NmIyMDQ5NzZlZWI4MzgxMGI0N2Q5NTg1NjNiNTJjNzZmNWRmMDI3NDBkNmQyOGYxZjY3M2FiYWViNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRsJJ_qnNuNQLIhxVDgDUuPw4_Tfv6aQI8LySkfsNmM)
> 
> Maybe your Sound Blaster's 64-bit Midi In port is not installed?

I only have Loopmidi as Midi IN port. The X-Fi Ti HD is from 2011, it plays midi but it doesn't seem to have midi input ports.
Now I understand, you're probably using a Sound Blaster that's much older than mine.

**Comment by nukeykt** [comment]
Added command line option to specify midi port until config file support is added. See readme for details

**Comment by Falcosoft** [comment]
> Added command line option to specify midi port until config file support is added. See readme for details

Hi,
Thanks for the fast update. I would like to report that the update works but it is somewhat misleading that is still always reports the name of port 0 as opened port regardless of the command line argument and the really opened (right) port.

![image](https://github.com/nukeykt/Nuked-SC55/assets/40074203/70f667dc-d29f-47fa-a317-ceae64314ccf)

**Comment by markanini** [comment]
> > Added command line option to specify midi port until config file support is added. See readme for details
> 
> Hi, Thanks for the fast update. I would like to report that the update works but it is somewhat misleading that it still always reports the name of port 0 as opened port regardless of the command line argument and the really opened (right) port.
> 
> ![image](https://private-user-images.githubusercontent.com/40074203/319381301-70f667dc-d29f-47fa-a317-ceae64314ccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjQ0MjUsIm5iZiI6MTcxMjYyNDEyNSwicGF0aCI6Ii80MDA3NDIwMy8zMTkzODEzMDEtNzBmNjY3ZGMtZDI5Zi00N2ZhLWEzMTctY2VhZTY0MzE0Y2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAwNTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMDkyYWIwYzc0ZjRiOWUxZGVkZjc5NTU3NGYxMTc1ZmQyYWY4MDFiZTAzOTA1ZWU4MDU4OWZmZGY0ODkxMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Ih99OfNgiG-vOzcL1Whewu4D-X0QVgg616VOKfjjgs)

Thanks for pointing out this quirk, it confused the heck out of me.
