### ISSUE TITLE
Errors when using in Anvil Studio

### ISSUE THREAD

**Issue by OpenRift412** [nukeykt/Nuked-SC55#58]
When using Nuked-SC55 in Anvil studio I get the following error: 
![image](https://github.com/nukeykt/Nuked-SC55/assets/29780788/bf2fc72a-10c9-4924-ac93-1ede9d0f1b14)

Also, loopMIDI automatically mutes the port and I get this error notification:
![image](https://github.com/nukeykt/Nuked-SC55/assets/29780788/91617cea-a5db-48a6-827b-afbe4f5b1dd1)

This issue happens on version 0.2.0-hotfix2

**Comment by Karmeck** [comment]
I suggest you test with the version found here, direct link to post. 
https://www.vogons.org/viewtopic.php?p=1255128#p1255128

**Comment by Falcosoft** [comment]
The most likely cause of your problem is that Anvil Studio also opened the same LoopMidi port as Midi Input that you set in Anvil Studio as Midi Output. Try to set Midi In port in Anvil Studio to none or make another dummy LoopMidi port and select it as Midi In port.

**Comment by OpenRift412** [comment]
> The most likely cause of your problem is that Anvil Studio also opened the same LoopMidi port as Midi Input port that you set in Anvil Studio as Midi Output port. Try to set Midi In port in Anvil Studio to none or make another dummy LoopMidi port and select it as Midi In port. (View -> Synthesizers, MIDI + Audio ports)

Okay, that seemed to work, thanks. Here's my setup for anyone else who runs into this issue:
![image](https://github.com/nukeykt/Nuked-SC55/assets/29780788/3d3d335f-bd2d-4582-b601-cac055a0ceb6)

I don't know how this could be made more automated in the future, but any ideas are welcome, I suppose.

**Comment by Falcosoft** [comment]
Hi,
Actually this problem has nothing to do with the emulator. It would happen the same way if you do not even start the emulator :)

**Comment by zaphod77** [comment]
correct. the emulator is 100% not at fault here.  midi feedback is always either a software configuration error, or a false positive in the midi virtual cable driver (loopbe1 is infamous for this).
