### ISSUE TITLE
SC-55 (v1.21) rom dump causes unknown write error and black screen after.

### ISSUE THREAD

**Issue by ThatRetroGuy** [nukeykt/Nuked-SC55#67]
Hii, im not sure what im doing wrong as ive named them as in the read me file,  

This is what happens as result when its trying to load the rom file's.

![Skærmbillede 2024-05-01 043247](https://github.com/nukeykt/Nuked-SC55/assets/76837099/7b67ffc9-1609-48c1-b2ad-9274d9d04e58)

during the black screen part it pushes this on loop.

![Skærmbillede 2024-05-01 043509](https://github.com/nukeykt/Nuked-SC55/assets/76837099/d2803418-f793-454d-a3e3-1f8128d8b0cb)

**Comment by chunkyjackson** [comment]
That ROM file you renamed "sc55_rom1.bin" is a dummy file it's not a valid ROM. I checked it in a hex editor. It just full of 00's 30's. It hasn't been released publicly (yet) here is a thread with more info: https://github.com/nukeykt/Nuked-SC55/issues/34

**Comment by ThatRetroGuy** [comment]
> That ROM file you renamed "sc55_rom1.bin" is a dummy file it's not a valid ROM. I checked it in a hex editor. It just full of 00's 30's. It hasn't been released publicly (yet) here is a thread with more info: #34

oh, darn, can we talke in a email or how?

**Comment by chunkyjackson** [comment]
I don't have it, if I did it would be already archived.

**Comment by ThatRetroGuy** [comment]
found a complete rom set of .1.21, works fine as exspected, so this case is done.
