### ISSUE TITLE
Using the real lcd as a display. 

### ISSUE THREAD

**Issue by Karmeck** [nukeykt/Nuked-SC55#71]
So I just got a sc-55 mk1. And wonder, could the lcd on here be used by the emulator?
Now I see that replacement lcds are not hard to come by, so testing this would not mean I have to rip out my own.

I guess the real/first question is, does the emulator emulate outputting information to a lcd?

**Comment by matt713** [comment]
what is the version of your mk1, v1.10, v1.20, etc?

**Comment by Karmeck** [comment]
> what is the version of your mk1, v1.10, v1.20, etc?

1.20

**Comment by matt713** [comment]
> 1.20

please, make a picture of the ROM inside, I just want to know the Part number of v1.20 ROM. I know v1.21 is "R15209363", but i've never seen v1.20.

**Comment by Karmeck** [comment]
> > 1.20
> 
> please, make a picture of the ROM inside, I just want to know the Part number of v1.20 ROM. I know v1.21 is "R15209363", but i've never seen v1.20.

I shall do this later today. Reminder set.

**Comment by Karmeck** [comment]
![20240508_173340](https://github.com/nukeykt/Nuked-SC55/assets/33399802/63c8a07c-5621-44ef-8ad8-13ba399ef16d)

**Comment by pachuco** [comment]
Unrelated, what's ROHM here? I associate that name with a certain mobile phone GM synth.

**Comment by Karmeck** [comment]
> Unrelated, what's ROHM here? I associate that name with a certain mobile phone GM synth.

I do not understand this question.

**Comment by pachuco** [comment]
> > Unrelated, what's ROHM here? I associate that name with a certain mobile phone GM synth.
> 
> I do not understand this question.

I see ROHM written on the part at the top and was wondering what it is. Because I've heard name ROHM elsewhere before.

**Comment by Karmeck** [comment]
> > > Unrelated, what's ROHM here? I associate that name with a certain mobile phone GM synth.
> > 
> > 
> > I do not understand this question.
> 
> I see ROHM written on the part at the top of the image, and was wondering what it is. Because I've heard name ROHM elsewhere before.

rcm2024t display

It's the back of the lcd.

**Comment by Karmeck** [comment]
> > 1.20
> 
> please, make a picture of the ROM inside, I just want to know the Part number of v1.20 ROM. I know v1.21 is "R15209363", but i've never seen v1.20.

I have news regarding scc-1A. See pm on vogons.
